"""empty message

Revision ID: 18e7a654fcbc
Revises: 4c0ab1b9369f
Create Date: 2025-12-12 00:40:58.866444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e7a654fcbc'
down_revision = '4c0ab1b9369f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tour_completed')

    # ### end Alembic commands ###
