"""final schema updates

Revision ID: 51fca6f41bf3
Revises: c0b9803c4834
Create Date: 2025-10-06 18:45:24.899687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fca6f41bf3'
down_revision = 'c0b9803c4834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.Date(), nullable=False))
        batch_op.create_unique_constraint('_user_date_uc', ['user_id', 'entry_date'])
        batch_op.create_index(batch_op.f('ix_log_entry_entry_date'), ['entry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entry_entry_date'))
        batch_op.drop_constraint('_user_date_uc', type_='unique')
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###
