"""initial migration with lean model

Revision ID: c8291103f790
Revises: 51fca6f41bf3
Create Date: 2025-10-08 17:59:51.061099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8291103f790'
down_revision = '51fca6f41bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.drop_column('key_results')
        batch_op.drop_column('challenges')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenges', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('key_results', sa.TEXT(), nullable=True))
        batch_op.drop_column('observations')

    # ### end Alembic commands ###
